---
title: "plot"
author: "Me"
date: "2026-02-22"
output: html_document
---



```{r}
library(tidyverse)


data <- readRDS("script1.rds")
col_names <- colnames(data)[1:3]

for (col_name in col_names) { 
  # We wrap the ggplot call in print() so it actually renders
  p <- ggplot(data, aes(x = .data[[col_name]], y = speedup_Macs2)) +
    geom_point() +
    theme_bw() +
    labs(
      x = col_name, 
      y = "Speedup Macs2 / quickHaplo in Seconds", 
      title = paste("Benchmarking Haplo Methods -", col_name)
    ) +
    theme(axis.text.x = element_text(angle = 45, hjust = 1))+
    geom_smooth(method = "lm", se = FALSE, color = "blue") # Add a linear regression line
  
  print(p) 
}
```


Plotting the memory use

```{r}
for (col_name in col_names) { 
  # We wrap the ggplot call in print() so it actually renders
  p <- ggplot(data, aes(x = .data[[col_name]], y = mem_ratio_Macs2)) +
    geom_point() +
    theme_bw() +
    labs(
      x = col_name, 
      y = "Memory Use Macs2 / quickHaplo in MB", 
      title = paste("Benchmarking Haplo Methods - Memory Use -", col_name)
    ) +
    theme(axis.text.x = element_text(angle = 45, hjust = 1))+
    geom_smooth(method = "lm", se = FALSE, color = "red") # Add a linear regression line
  
  print(p) 
}
```


