library(AlphaSimR)
fix(runMacs)
runMacs_3 <- function (nInd, nChr = 1, segSites = NULL, inbred = FALSE, species = "GENERIC", 
          split = NULL, ploidy = 2L, manualCommand = NULL, manualGenLen = NULL, 
          nThreads = NULL) 
{
  # if (is.null(nThreads)) {
  #   nThreads = getNumThreads()
  # }
  nInd = as.integer(nInd)
  nChr = as.integer(nChr)
  ploidy = as.integer(ploidy)
  if (nChr < nThreads) {
    nThreads = nChr
  }
  seed = sapply(1:nChr, function(x) {
    as.character(sample.int(1e+08, 1))
  })
  if (is.null(segSites)) {
    segSites = rep(0L, nChr)
  }
  else if (length(segSites) == 1L) {
    segSites = rep(as.integer(segSites), nChr)
  }
  popSize = ifelse(inbred, nInd, ploidy * nInd)
  if (!is.null(manualCommand)) {
    if (is.null(manualGenLen)) 
      stop("You must define manualGenLen")
    command = paste0(popSize, " ", manualCommand, " -s ")
    genLen = manualGenLen
  }
  else {
    species = toupper(species)
    if (species == "GENERIC") {
      genLen = 1
      Ne = 100
      speciesParams = "1E8 -t 1E-5 -r 4E-6"
      speciesHist = "-eN 0.25 5.0 -eN 2.50 15.0 -eN 25.00 60.0 -eN 250.00 120.0 -eN 2500.00 1000.0"
    }
    else if (species == "CATTLE") {
      cattleChrSum = 2.8e+09
      cattleChrBp = cattleChrSum/30
      recRate = 9.26e-09
      genLen = recRate * cattleChrBp
      mutRate = 9.4e-09
      Ne = 90
      histNe = c(120, 250, 350, 1000, 1500, 2000, 2500, 
                 3500, 7000, 10000, 17000, 62000)
      histGen = c(3, 6, 12, 18, 24, 154, 454, 654, 1754, 
                  2354, 3354, 33154)
      speciesParams = paste(c(round(cattleChrBp), "-t", 
                              mutRate * 4 * Ne, "-r", recRate * 4 * Ne), collapse = " ")
      histNe = histNe/Ne
      histGen = histGen/(4 * Ne)
      speciesHist = NULL
      for (i in seq_len(length(histNe))) {
        speciesHist = paste(speciesHist, "-eN", histGen[i], 
                            histNe[i])
      }
    }
    else if (species == "WHEAT") {
      genLen = 1.43
      Ne = 50
      speciesParams = "8E8 -t 4E-7 -r 3.6E-7"
      speciesHist = "-eN 0.03 1 -eN 0.05 2 -eN 0.10 4 -eN 0.15 6 -eN 0.20 8 -eN 0.25 10 -eN 0.30 12 -eN 0.35 14 -eN 0.40 16 -eN 0.45 18 -eN 0.50 20 -eN 1.00 40 -eN 2.00 60 -eN 3.00 80 -eN 4.00 100 -eN 5.00 120 -eN 10.00 140 -eN 20.00 160 -eN 30.00 180 -eN 40.00 200 -eN 50.00 240 -eN 100.00 320 -eN 200.00 400 -eN 300.00 480 -eN 400.00 560 -eN 500.00 640"
    }
    else if (species == "MAIZE") {
      genLen = 2
      Ne = 100
      speciesParams = "2E8 -t 5E-6 -r 4E-6"
      speciesHist = "-eN 0.03 1 -eN 0.05 2 -eN 0.10 4 -eN 0.15 6 -eN 0.20 8 -eN 0.25 10 -eN 0.30 12 -eN 0.35 14 -eN 0.40 16 -eN 0.45 18 -eN 0.50 20 -eN 2.00 40 -eN 3.00 60 -eN 4.00 80 -eN 5.00 100"
    }
    else {
      stop(paste("No rules for species", species))
    }
    if (is.null(split)) {
      splitI = ""
      splitJ = ""
    }
    else {
      stopifnot(popSize%%2 == 0)
      splitI = paste(" -I 2", popSize%/%2, popSize%/%2)
      splitJ = paste(" -ej", split/(4 * Ne) + 1e-06, "2 1")
    }
    command = paste0(popSize, " ", speciesParams, splitI, 
                     " ", speciesHist, splitJ, " -s ")
  }
  if (!is.null(manualGenLen)) {
    genLen = manualGenLen
  }
  if (length(genLen) == 1) {
    genLen = rep(genLen, nChr)
  }
  macsOut = MaCS(command, segSites, inbred, ploidy, nThreads, 
                 seed)
  dim(macsOut$geno) = NULL
  nLoci = sapply(macsOut$genMap, length)
  isLimited = segSites > 0
  if (any(nLoci[isLimited] != segSites[isLimited])) {
    stop("MaCS did not return enough segSites, use segSites=NULL to return all sites generated by MaCS")
  }
  genMap = vector("list", nChr)
  for (i in seq_len(nChr)) {
    genMap[[i]] = genLen[i] * c(macsOut$genMap[[i]] - macsOut$genMap[[i]][1])
    names(genMap[[i]]) = paste(i, 1:length(genMap[[i]]), 
                               sep = "_")
  }
  names(genMap) = as.character(1:nChr)
  output = new("MapPop", nInd = nInd, nChr = nChr, ploidy = ploidy, 
               nLoci = nLoci, geno = macsOut$geno, genMap = genMap, 
               centromere = sapply(genMap, max)/2, inbred = inbred)
  return(output)
}



fix(runMacs2)
function (nInd, nChr = 1, segSites = NULL, Ne = 100, bp = 1e+08, 
          genLen = 1, mutRate = 2.5e-08, histNe = c(500, 1500, 6000, 
                                                    12000, 1e+05), histGen = c(100, 1000, 10000, 1e+05, 
                                                                               1e+06), inbred = FALSE, split = NULL, ploidy = 2L, returnCommand = FALSE, 
          nThreads = NULL) 
{
  stopifnot(length(histNe) == length(histGen))
  Ne = Ne * (ploidy/2L)
  if (!is.null(histNe)) {
    histNe = histNe * (ploidy/2L)
  }
  speciesParams = paste(bp, "-t", 4 * Ne * mutRate, "-r", 
                        4 * Ne * genLen/bp)
  speciesHist = ""
  if (length(histNe) > 0) {
    histNe = histNe/Ne
    histGen = histGen/(4 * Ne)
    for (i in seq_len(length(histNe))) {
      speciesHist = paste(speciesHist, "-eN", histGen[i], 
                          histNe[i])
    }
  }
  if (is.null(split)) {
    command = paste(speciesParams, speciesHist)
  }
  else {
    popSize = ifelse(inbred, nInd, ploidy * nInd)
    command = paste(speciesParams, paste("-I 2", popSize%/%2, 
                                         popSize%/%2), speciesHist, paste("-ej", split/(4 * 
                                                                                          Ne) + 1e-06, "2 1"))
  }
  if (returnCommand) {
    return(command)
  }
  return(runMacs(nInd = nInd, nChr = nChr, segSites = segSites, 
                 inbred = inbred, species = "TEST", split = NULL, ploidy = ploidy, 
                 manualCommand = command, manualGenLen = genLen, nThreads = nThreads))
}
